general:
    # The max length of characters in a line item lore can have (to keep text on screen)
    lore_line_length: 60
    # If disabled server operators will not recieve cooldowns
    give_op_cooldowns: true
    # If disabled players in creative or spectator will not recieve cooldowns
    give_immune_cooldowns: true
    # If set to false cooldown messages for abilities will not be sent to players
    send_cooldown_messages: true
    # Determines where to send cooldown messages to players (Can use 'CHAT' or 'HOTBAR')
    cooldown_message_appearance: 'CHAT'
    # If set to true then players can use color codes '&' for item names in custom anvil recipes or hex codes formatted as such '(hex:#ffffff)'
    allow_rename_colors: false
    # If set to true then will print debug error warnings to the console
    debug_messages: true
    # This setting will automatically refresh custom item abilities and lore when an inventory is opened. This may cause lag if there are too many custom items on the server, turn off if you experience lag with this
    refresh_on_open: true
messages:
    # Message displayed to players who try to activate abilities that are on cooldown
    abilityCooldown: "&cYou cannot use %ability% &cfor another &e%cooldown% &cseconds!"