name: UIFramework
version: ${project.version}
author: JewishBanana
main: ${mainClass}
description: Framework for custom items.
api-version: 1.17

commands:
    uiframework:
        usage: /uiframework <give|enchant|summon|recipes|entities|help|reload|>...
        description: Universal command for the plugin. Use /uiframework help, for more information.
        aliases: [ui, uitems]
        
permissions:
    uiframework.*:
        description: Gives access to all commands of UIFramework.
        children:
            uiframework.help: true
            uiframework.reload: true
            uiframework.give: true
            uiframework.recipes: true
            uiframework.modifyRecipes: true
            uiframework.enchant: true
    uiframework.help:
        description: Allows you to use the help command.
    uiframework.reload:
        description: Allows you to use the reload command.
    uiframework.give:
        description: Allows you to give yourself and other players custom items.
    uiframework.recipes:
        description: Allows you to view the item recipes by command.
    uiframework.modifyRecipes:
        description: Allows you to delete and add recipes for items.
    uiframework.enchant:
        description: Allows you to use the enchant command to apply custom enchants to items.
    uiframework.summon:
        description: Allows you to use the summon command to summon custom entities.
    uiframework.entities:
        description: Allows you to use the entities command to display admin information and manipulate custom entities.