name: UIFramework
version: 2.0.2
author: JewishBanana
main: com.jewishbanana.uiframework.UIFramework
description: Framework for custom items.
api-version: 1.17

commands:
    uiframework:
        usage: /uiframework <help|give>...
        description: Universal command for the plugin. Use /uiframework help, for more information.
        aliases: [ui, uitems]
        
permissions:
    uiframework.*:
        description: Gives access to all commands of UIFramework.
        children:
            uiframework.help: true
            uiframework.reload: true
            uiframework.give: true
            uiframework.recipes: true
            uiframework.modifyRecipes: true
    uiframework.help:
        description: Allows you to use the help command.
    uiframework.reload:
        description: Allows you to use the reload command.
    uiframework.give:
        description: Allows you to give yourself and other players custom items.
    uiframework.recipes:
        description: Allows you to view the item recipes by command.
    uiframework.modifyRecipes:
        description: Allows you to delete and add recipes for items.